[server]
headless = true
enableCORS = false
enableWebsocketCompression = false
fileWatcherType = "none"
scriptHealthCheckEnabled = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = false
